### PR TITLE
add cypher query column to metapath table

### PR DESCRIPTION
**Pull request by vincerubinetti**
image

@dhimmel @dongbohu

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@dongbohu bear with me, my home computer's eslint and prettier settings are different than my work computer, and so the code is being reformatted incorrectly. Trying to fix. The actual lines changed is under 10 I think.

**Comment by vincerubinetti** [comment]
@dongbohu I don't understand why, but on my home computer, eslint --fix is replacing single quotes with double quotes, even though I have `"quotes": ["error", "single"` in my `.eslintrc`. It seems to be only doing doubles for strings in jsx or html, not in regular javascript lines. So maybe it has something to do with the eslint html plugin. For now, just manually formatting the quotes to single.

**Comment by dhimmel** [comment]
The appearance looks good to me.

**Comment by vincerubinetti** [comment]
> The appearance looks good to me.

Tooltip text okay?

Code review might not really be necessary as this is just adding another html column to a table.

**Comment by vincerubinetti** [comment]
> @vincerubinetti: Code looks good and I am approving it. About the eslint weridness, is it possible that you have multiple eslint config files on your home computer and the rules messed up?

Yeah I think I figured it out. I had to change a setting in my prettier vscode extension that told it to respect the config rules instead of the vscode settings default.

**Pull request merged**
