### PR TITLE
update package dependencies

### PR DESCRIPTION
**Pull request by vincerubinetti**

### CODE REVIEW

**Comment by cgreene** [comment]
@vincerubinetti / @dongbohu did this get tested? It looks like the frontend is currently broken.

Firefox:
Screen Shot 2019-09-21 at 8 25 42 AM

**Comment by cgreene** [comment]
Chrome: 
Screen Shot 2019-09-21 at 8 26 03 AM

**Comment by vincerubinetti** [comment]
@cgreene  Yes it was tested. I'm looking at the website now on firefox and chrome and it looks fine. Try doing a hard refresh on your cache. This happens sometimes when the javascript file gets updated but the css file has not yet updated on the server. Seems to be a github issue.

**Comment by vincerubinetti** [comment]
Also here is a related gh issue where people talk about building CRA apps in a non-split manner:
https://github.com/facebook/create-react-app/issues/5306

**Pull request merged**
