### PR TITLE
Update package dependencies

### PR DESCRIPTION
**Pull request by vincerubinetti**
Local `npm run start`

chrome
image

firefox:
image

### CODE REVIEW

**Comment by vincerubinetti** [comment]
`npm run build`

chrome
image


firefox
image

**Comment by vincerubinetti** [comment]
Okay so the problem is the hetmech css isn't being loaded, as expected. Now to figure out why.

**Comment by vincerubinetti** [comment]
@cgreene Okay I know what the problem is. I rely on [this script](https://github.com/greenelab/hetmech-frontend/blob/master/scripts/build-non-split.js) to hack `create-react-app` to make sure it always outputs the javascript and CSS files with the same name (which I think it's stupid it doesn't do that by default), so we can hot-link to it reliably from het.io.

React must've made a change that makes this script not work any more, but just for the css. I'll try to fix it.

It works locally, even when doing a production build, because the `index.html` used to run the app gets automatically updated with the dynamically generated js/css filenames.

**Comment by cgreene** [comment]
Woo! Glad we've got a cause!

**Comment by vincerubinetti** [comment]
It's a shame that `create-react-app` doesn't provide an option to output a consistent build file name (or just do it by default). We can change this more robustly by "ejecting" create react app, but then we have to maintain all the sub-dependencies ourselves, sort of defeating the convenience purpose of using CRA in the first place.

So even though this is an insidious problem (doesn't show up locally), we still probably don't to eject. @dongbohu Maybe we can create a CI check that simply makes sure that a file named `main.css` and `main.js` exist in the build folder (and were the latest ones to be built), and throw an error if not.

**Comment by cgreene** [comment]
I think @dongbohu is traveling FYI.

**Comment by vincerubinetti** [comment]
Also here is a related gh issue where people talk about building CRA apps in a non-split manner:
https://github.com/facebook/create-react-app/issues/5306

**Pull request merged**
