### PR TITLE
add csv download button, load tooltips from external json, add search icon

### PR DESCRIPTION
**Pull request by vincerubinetti**
This PR:
- adds a csv download button for the metapath result table
- changes the tooltip text from being specified in the javascript files to being loaded from external `.json` files
- add search magnifying glass icon to node search bar
- improves wrapping behavior of dynamic field component
- improves some css
- fixes metapath table not expanding regression bug
- other minor improvements

Live temporary preview:
https://www.vincentrubinetti.com/hetmech/?source=14195&target=14729

### CODE REVIEW

**Comment by dhimmel** [comment]
Let's get a code review from @dongbohu.

Live preview looks good (although I assume the path frame is not part of this PR).

I don't think the name assigned to the CSV download (refs https://github.com/greenelab/hetmech-frontend/issues/12) is ideal: `hetio-metapaths Escitalopram alcohol-depende.csv`. Perhaps we could separate parts using underscores not spaces and remove the leading `hetio-`. We should probably concatenate the names separately. What sluggificaiton is being done to the names?

**Comment by vincerubinetti** [comment]
> although I assume the path frame is not part of this PR).
Correct.

> I don't think the name assigned to the CSV download is ideal. What sluggificaiton is being done to the names?

Right now, I'm simply replacing all non-alphanumeric characters with dashes and truncating the string at 15 characters. This process is applied to the souce node name and target node name. Then the three "sections" (prefix, source node name, target node name) are combined, separated by spaces.

We can do whatever you'd like.

**Comment by dhimmel** [comment]
> Right now, I'm simply replacing all non-alphanumeric characters with dashes and truncating the string at 15 characters. This process is applied to the souce node name and target node name.

Good

> Then the three "sections" (prefix, source node name, target node name) are combined, separated by spaces.

Good besides can we use underscore instead of space, since spaces are a bit annoying for terminal users sometimes.

**Comment by vincerubinetti** [comment]
Okay I'll change space to underscore. What would you like as a prefix, if any, for now?

**Comment by dhimmel** [comment]
> What would you like as a prefix, if any, for now?

I think `metapaths` is sufficient. I doubt users will have many other files or products that use the term metapaths.

**Comment by vincerubinetti** [comment]
@dongbohu @dhimmel I'm going to make sure I split up the PRs more logically going forward. I know this is a mish-mash of fairly disparate things.

**Pull request merged**
