### PR TITLE
Revert "update package dependencies"

### PR DESCRIPTION
**Pull request by cgreene**
Reverts greenelab/hetmech-frontend#147

Attempt to fix frontend.

### CODE REVIEW

**Comment by cgreene** [comment]
This passed CI. I'm going to merge it to see if it gets a fixed frontend (if CI is set to deploy), since a bunch of folks from Rowan yesterday were interested in using it. Worst case scenario is that we can re-apply #147 if this doesn't fix things.

**Comment by cgreene** [comment]
Wrong button on that close 😂

**Comment by dongbohu** [comment]
Is it working okay on Firefox now? I don't have access to firefox right now.

**Comment by cgreene** [comment]
It doesn't appear to be. I think it may be broken from https://github.com/hetio/frontend-components/pull/45/files

**Comment by vincerubinetti** [comment]
Are you sure this wasn't a caching issue. That PR was tested and it looked normal on my machine in both browsers. Also those screenshots look very much like the javascript file was updated but the CSS file wasn't. I've run into odd caching issues that I believe are github-pages fault that look just like that, and it just requires time to resolve.

**Comment by vincerubinetti** [comment]
Just ran the app locally (without this revert PR) and it looks normal: 

image

I don't see how anything in the previous PR could've caused the errors I see in the broken screenshots. In those screenshots, `global.css` from het.io is clearly being loaded, but the hetmech specific css is not. The PR only updates external packages. 

I'm almost certain this was some type of caching error. However if you're concerned that other people might be using it soon, it's fine to leave the revert in place for now.

**Comment by cgreene** [comment]
It works for me now in the current live version. I'm pretty confident that it wasn't a caching issue. It didn't work on the machines of a few people I also met with during the afternoon yesterday, and they never would have loaded het.io before.

We can re-apply #147 and see if things keep working!

**Comment by vincerubinetti** [comment]
Caching maybe isn't the best word. I've run into issues with github pages somehow serving the new version of a javascript file but the old version of a css file after a recent merge, and it inexplicably continued until I waited a bit and also re-requested it a bunch of times.

Are you okay with reapplying #147 now, or are more people going to use it this weekend. I will be around to debug when/if the issue returns. And again, things were working fine locally, so if this truly is a non-caching error, it seems we can only see it when it actually gets deployed to github pages.

**Comment by cgreene** [comment]
I told folks I would email them when it was back up - I haven't sent it yet.

If you're around to try things out I'm happy for it to happen this weekend, but I also don't mind waiting to next week.

Let me know what you decide, and I'll either send out the emails or wait for a bit. Thanks!

**Comment by vincerubinetti** [comment]
Let me try it right now because I want to find out what is causing this. If I can't find the source of the issue within an hour, I'd say we'll re-revert (re-re-revert?) and send out the email.

**Comment by cgreene** [comment]
Sounds good!

**Comment by vincerubinetti** [comment]
Also here is a related gh issue where people talk about building CRA apps in a non-split manner:
https://github.com/facebook/create-react-app/issues/5306

**Pull request merged**
